language: php

php:
  - 5.5

before_script:
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=./vendor/panadas/phpcs-standard/src/Panadas/ ./src
  - ./vendor/bin/php-cs-fixer fix --dry-run --verbose --fixers=-psr0 ./src
