language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=./vendor/panadas/phpcs-standard/src/Panadas/ ./src
